// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;


    /// <summary>
    /// <para>
    /// Server side food FermentedWheatEthanol definition for the "FermentedWheatEthanol" FermentedWheatEthanol. 
    /// This object inherits the FoodFermentedWheatEthanol base class to allow for consumption mechanics.
    /// </para>
    /// <para>More information about FoodFermentedWheatEthanol objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.FermentedWheatEthanols.FoodFermentedWheatEthanol.html</para>
    /// </summary>
    /// <remarks>
    /// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
    /// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
    /// </remarks>
    [Serialized] // Tells the save/load system this object needs to be serialized. 
    [LocDisplayName("Fermented Ethanol")] // Defines the localized name of the FermentedWheatEthanol.
    [Weight(300)] // Defines how heavy the FermentedWheatEthanol is.

    [Ecopedia("Food", "Product", createAsSubPage: true)]
    [LocDescription("Fermented Wheat or Corn into Ethanol.")] //The tooltip description for the food FermentedWheatEthanol.
    public partial class FermentedEthanolItem : FoodItem
    {


        /// <summary>The amount of calories awarded for eating the food FermentedWheatEthanol.</summary>
        public override float Calories => 0;
        /// <summary>The nutritional value of the food FermentedWheatEthanol.</summary>
        public override Nutrients Nutrition => new Nutrients() { Carbs = 0, Fat = 0, Protein = 0, Vitamins = 0 };

        /// <summary>Defines the default time it takes for this FermentedWheatEthanol to spoil. This value can be modified by the inventory this FermentedWheatEthanol currently resides in.</summary>
        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);
    }



    [RequiresSkill(typeof(MixologySkill), 6)]
    [Ecopedia("Food", "Fermented Alcohol", subPageName: "Fermented Ethanol Item")]
    public partial class FermentedWheatEthanolRecipe : RecipeFamily
    {
        public FermentedWheatEthanolRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "FermentedWheatEthanol",  //noloc
                displayName: Localizer.DoStr("Ferment Wheat Ethanol"),

                // Defines the ingredients needed to craft this recipe. An ingredient FermentedWheatEthanols takes the following inputs
                // type of the FermentedWheatEthanol, the amount of the FermentedWheatEthanol, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(FlourItem), 50, typeof(MixologySkill), typeof(MixologyLavishResourcesTalent)),
                    new IngredientElement(typeof(YeastItem), 5, typeof(MixologySkill), typeof(MixologyLavishResourcesTalent)),
                    new IngredientElement(typeof(SugarItem), 10, typeof(MixologySkill), typeof(MixologyLavishResourcesTalent)),
                    new IngredientElement(typeof(WoodenBarrelItem), 1, true),
                },

                // Define our recipe output FermentedWheatEthanols.
                // For every output FermentedWheatEthanol there needs to be one CraftingElement entry with the type of the final FermentedWheatEthanol and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<FermentedEthanolItem>(1),
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 1; // Defines how much experience is gained when crafted.

            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(800, typeof(MixologySkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(FermentedWheatEthanolRecipe), start: 6f, skillType: typeof(MixologySkill), typeof(MixologyFocusedSpeedTalent), typeof(MixologyParallelSpeedTalent));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "FermentedWheatEthanol"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Ferment Wheat Ethanol"), recipeType: typeof(FermentedWheatEthanolRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(FermentingBarrelObject), recipe: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }



}
