// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Roasted Peanuts")]
    [Weight(200)]
    [Tag("Food")]
    [Ecopedia("Food", "Product", createAsSubPage: true)]
    [LocDescription("Peanuts that have be deshelled, washed, roasted, and salted.")]
    public partial class RoastedPeanutsItem : FoodItem
    {

        public override float Calories => 200;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 6,
            Fat = 15,
            Protein = 9,
            Vitamins = 0
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);

    }




    //Recipe


    [RequiresSkill(typeof(BakingSkill), 4)]
    [Ecopedia("Food", "Product", subPageName: "Roasted Peanuts Item")]
    public partial class RoastedPeanutsRecipe : RecipeFamily
    {
        public RoastedPeanutsRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "RoastedPeanuts",  //noloc
                displayName: Localizer.DoStr("Roast Peanuts"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(PeanutItem), 10, typeof(BakingSkill), typeof(BakingLavishResourcesTalent)),
                    new IngredientElement(typeof(SaltItem), 1, typeof(BakingSkill), typeof(BakingLavishResourcesTalent)),                    
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<RoastedPeanutsItem>(5),
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(500, typeof(BakingSkill));

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(RoastedPeanutsRecipe),
                start: 3f,
                skillType: typeof(BakingSkill), typeof(BakingFocusedSpeedTalent), typeof(BakingParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Roast Peanuts"), recipeType: typeof(RoastedPeanutsRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(BakeryOvenObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
