// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;


    /// <summary>
    /// <para>
    /// Server side food Glucose definition for the "Glucose" Glucose. 
    /// This object inherits the FoodGlucose base class to allow for consumption mechanics.
    /// </para>
    /// <para>More information about FoodGlucose objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Glucoses.FoodGlucose.html</para>
    /// </summary>
    /// <remarks>
    /// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
    /// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
    /// </remarks>
    [Serialized] // Tells the save/load system this object needs to be serialized. 
    [LocDisplayName("Glucose")] // Defines the localized name of the Glucose.
    [Weight(300)] // Defines how heavy the Glucose is.

    [Ecopedia("Food", "Product", createAsSubPage: true)]
    [LocDescription("Made from treated Corn Starch.")] //The tooltip description for the food Glucose.
    public partial class GlucoseItem : FoodItem
    {


        /// <summary>The amount of calories awarded for eating the food Glucose.</summary>
        public override float Calories => 0;
        /// <summary>The nutritional value of the food Glucose.</summary>
        public override Nutrients Nutrition => new Nutrients() { Carbs = 0, Fat = 0, Protein = 0, Vitamins = 0 };

        /// <summary>Defines the default time it takes for this Glucose to spoil. This value can be modified by the inventory this Glucose currently resides in.</summary>
        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);
    }



    [RequiresSkill(typeof(BiochemistSkill), 2)]
    public partial class GlucoseRecipe : RecipeFamily
    {
        public GlucoseRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Glucose",  //noloc
                displayName: Localizer.DoStr("Enzyme Treatment of Corn Starch"),

                // Defines the ingredients needed to craft this recipe. An ingredient Glucoses takes the following inputs
                // type of the Glucose, the amount of the Glucose, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(CornStarchItem), 50, typeof(BiochemistSkill), typeof(BiochemistLavishResourcesTalent)),
                    new IngredientElement(typeof(GlucoamylaseItem), 20, typeof(BiochemistSkill), typeof(BiochemistLavishResourcesTalent)),
                },

                // Define our recipe output Glucoses.
                // For every output Glucose there needs to be one CraftingElement entry with the type of the final Glucose and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<GlucoseItem>(5),
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 1; // Defines how much experience is gained when crafted.

            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(800, typeof(BiochemistSkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(GlucoseRecipe), start: 8f, skillType: typeof(BiochemistSkill), typeof(BiochemistFocusedSpeedTalent), typeof(BiochemistParallelSpeedTalent));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Glucose"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Enzyme Treatment of Corn Starch"), recipeType: typeof(GlucoseRecipe));
            this.ModsPostInitialize();

    // Register our RecipeFamily instance with the crafting system so it can be crafted.
    CraftingComponent.AddRecipe(tableType: typeof(ChemicalLaboratoryObject), recipe: this);
    }

    /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
    partial void ModsPreInitialize();

    /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
    partial void ModsPostInitialize();
}



}
