// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Time;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Aluminum Sheet")]
    [Weight(100)]

    [Ecopedia("Items", "Products", subPageName: "Aluminum Sheet Item")]
    [LocDescription("Aluminum pressed into sheets")]
    public partial class AluminumSheetItem : Item
    {

    }




    //Recipe

    [RequiresModule(typeof(MachinistTableObject))]
    [RequiresSkill(typeof(MechanicsSkill), 1)]
    [Ecopedia("Items", "Products", subPageName: "Aluminum Sheet Item")]
    public partial class AluminumSheetRecipe : RecipeFamily
    {
        public AluminumSheetRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "AluminumSheet",  //noloc
                displayName: Localizer.DoStr("Aluminum Sheet"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(AluminumBarItem), 1, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
                   

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<AluminumSheetItem>(1),
                });

            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 1f;


            this.LaborInCalories = CreateLaborInCaloriesValue(60, typeof(MechanicsSkill));


            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(AluminumSheetRecipe),
                start: 2f,
                skillType: typeof(MechanicsSkill), typeof(MechanicsFocusedSpeedTalent), typeof(MechanicsParallelSpeedTalent));


            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Aluminum Sheet"), recipeType: typeof(AluminumSheetRecipe));
            this.ModsPostInitialize();


            CraftingComponent.AddRecipe(tableType: typeof(ScrewPressObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();
    }
}