// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Time;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Aluminum Bar")]
    [Weight(300), MaxStackSize(20), Carried]
    [Ecopedia("Items", "Products", subPageName: "Aluminum Bar Item")]
    [LocDescription("Aluminum shaped into a bar.")]
    public partial class AluminumBarItem : Item
    {

    }




    //Recipe


    [RequiresSkill(typeof(AdvancedSmeltingSkill), 1)]
    [Ecopedia("Items", "Products", subPageName: "Aluminum Bar Item")]
    public partial class AluminumBarRecipe : RecipeFamily
    {
        public AluminumBarRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "AluminumBar",  //noloc
                displayName: Localizer.DoStr("Aluminum Bar"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(AluminumCrystalsItem), 15, typeof(AdvancedSmeltingSkill), typeof(AdvancedSmeltingLavishResourcesTalent)),
                    new IngredientElement(typeof(CeramicMoldItem), 5, typeof(AdvancedSmeltingSkill), typeof(AdvancedSmeltingLavishResourcesTalent)),

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<AluminumBarItem>(5),
                });

            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 0.5f;


            this.LaborInCalories = CreateLaborInCaloriesValue(50, typeof(AdvancedSmeltingSkill));


            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(AluminumBarRecipe),
                start: 1f,
                skillType: typeof(AdvancedSmeltingSkill), typeof(AdvancedSmeltingFocusedSpeedTalent), typeof(AdvancedSmeltingParallelSpeedTalent));


            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Aluminum Bar"), recipeType: typeof(AluminumBarRecipe));
            this.ModsPostInitialize();


            CraftingComponent.AddRecipe(tableType: typeof(BlastFurnaceObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();
    }
}