// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from RecipeTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    // Ingredient Item
    [Serialized]
    [LocDisplayName("Coal Powder")]
    [Weight(100)]
    [Ecopedia("Items", "Products", createAsSubPage: true)]
    [LocDescription("A fine powder made from crushed coal, used in various industrial processes and crafting.")]
    public partial class CoalPowderItem : Item
	{
    }

    // Recipe
    [RequiresSkill(typeof(MillingSkill), 2)]
    [Ecopedia("Items", "Products", subPageName: "Coal Powder")]
    public partial class CoalPowderRecipe : RecipeFamily
    {
        public CoalPowderRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CoalPowder",  //noloc
                displayName: Localizer.DoStr("Coal Powder"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(CrushedCoalItem), 1, typeof(MillingSkill), typeof(MillingLavishResourcesTalent)), // Base material
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<CoalPowderItem>(20), // Produces 20 units of Coal Powder
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(60, typeof(MillingSkill)); // Moderate labor requirement
            this.CraftMinutes = CreateCraftTimeValue(typeof(CoalPowderRecipe), .5f, typeof(MillingSkill), typeof(MillingFocusedSpeedTalent), typeof(MillingParallelSpeedTalent));

            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Coal Powder"), typeof(CoalPowderRecipe));
            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(typeof(MillObject), this); // Can be crafted in a Mill
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
