// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from RecipeTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    //Item
    [Serialized]
    [LocDisplayName("Steel Canister")]
    [Weight(100)]    
    [Ecopedia("Items", "Products", createAsSubPage: true)]
    [LocDescription("A durable container crafted from steel, used for storing gases and liquids.")]
    public partial class SteelCanisterItem : Item
    {
    }

    // Recipe
    [RequiresModule(typeof(ElectricStampingPressObject))]
    [RequiresSkill(typeof(IndustrySkill), 2)]
    [Ecopedia("Items", "Products", subPageName: "Steel Canister")]
    public partial class SteelCanisterRecipe : RecipeFamily
    {
        public SteelCanisterRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Steel Canister",  //noloc
                displayName: Localizer.DoStr("Steel Canister"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(SteelPlateItem), 3, typeof(IndustrySkill), typeof(IndustryLavishResourcesTalent)), 
                    new IngredientElement(typeof(WeldingRodItem), 1, typeof(IndustrySkill), typeof(IndustryLavishResourcesTalent)), 
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<SteelCanisterItem>(1), 
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(60, typeof(IndustrySkill)); 
            this.CraftMinutes = CreateCraftTimeValue(typeof(SteelCanisterRecipe), 2f, typeof(IndustrySkill)); 

            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Steel Canister"), typeof(SteelCanisterRecipe));
            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(typeof(ElectricMachinistTableObject), this); 
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
