// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Time;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Welding Rod")]
    [Weight(100)]

    [Ecopedia("Items", "Products", subPageName: "Welding Rod Item")]
    [LocDescription("A rod made of steel and with cellulose flux coating")]
    public partial class WeldingRodItem : Item
    {
        
    }




    //Recipe

    [RequiresModule(typeof(BlacksmithTableObject))]
    [RequiresSkill(typeof(AdvancedSmeltingSkill), 2)]
    [Ecopedia("Items", "Products", subPageName: "Welding Rod Item")]
    public partial class WeldingRodRecipe : RecipeFamily
    {
        public WeldingRodRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "WeldingRod",  //noloc
                displayName: Localizer.DoStr("Welding Rod"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(SteelBarItem), 1, typeof(AdvancedSmeltingSkill), typeof(AdvancedSmeltingLavishResourcesTalent)),
                    new IngredientElement(typeof(CelluloseFiberItem), 1, typeof(AdvancedSmeltingSkill), typeof(AdvancedSmeltingLavishResourcesTalent)),

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<WeldingRodItem>(2),
                });

            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 0.5f;


            this.LaborInCalories = CreateLaborInCaloriesValue(15, typeof(AdvancedSmeltingSkill));


            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(WeldingRodRecipe),
                start: 1f,
                skillType: typeof(AdvancedSmeltingSkill), typeof(AdvancedSmeltingFocusedSpeedTalent), typeof(AdvancedSmeltingParallelSpeedTalent));


            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Welding Rod"), recipeType: typeof(WeldingRodRecipe));
            this.ModsPostInitialize();


            CraftingComponent.AddRecipe(tableType: typeof(BlastFurnaceObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();
    }
}