// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Bong")]
    [Weight(150)]
    [MaxStackSize(420)]
    [LocDescription("A bong (also known as a water pipe), is a filtration device generally used for smoking cannabis.")]
    public partial class BongItem : Item
    {


    }



    //Recipe


    [RequiresSkill(typeof(GlassworkingSkill), 4)]
    public partial class BongRecipe : RecipeFamily
    {
        public BongRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Bong",  //noloc
                displayName: Localizer.DoStr("Bong"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(GlassItem), 2, typeof(GlassworkingSkill), typeof(GlassworkingLavishResourcesTalent)),
                    new IngredientElement(typeof(ColoredPowderItem), 10, typeof(GlassworkingSkill), typeof(GlassworkingLavishResourcesTalent)),

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<BongItem>(1)
                });
            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1f;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(BongRecipe), start: 3f, skillType: typeof(GlassworkingSkill), typeof(GlassworkingFocusedSpeedTalent), typeof(GlassworkingParallelSpeedTalent));

            
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Bong"), recipeType: typeof(BongRecipe));
            this.ModsPostInitialize();


    CraftingComponent.AddRecipe(tableType: typeof(GlassworksObject), recipe: this);
    }

    partial void ModsPreInitialize();

    partial void ModsPostInitialize();
}
}