// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Flax Egg")]
    [Weight(72)]
    [MaxStackSize(420)]
    [LocDescription("Ground Flaxseed cooked with water.  An alternative to Eggs. ")]
    public partial class FlaxEggItem : FoodItem
    {

        public override float Calories => 100;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 15,
            Fat = 0,
            Protein = 0,
            Vitamins = 2
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);

    }




    //Recipe


    [RequiresSkill(typeof(CookingSkill), 4)]

    public partial class FlaxEggRecipe : RecipeFamily
    {
        public FlaxEggRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "FlaxEgg",  //noloc
                displayName: Localizer.DoStr("Flax Egg"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(GroundFlaxseedItem), 10, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),
                    
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<FlaxEggItem>(10),   
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(FlaxEggRecipe),
                start: 2f,
                skillType: typeof(CookingSkill), typeof(CookingFocusedSpeedTalent), typeof(CookingParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Flax Egg"), recipeType: typeof(FlaxEggRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CastIronStoveObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
