// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Ground Flaxseed")]
    [Weight(72)]
    [MaxStackSize(420)]
    [LocDescription("Flax seeds grinded down into a powder. ")]
    public partial class GroundFlaxseedItem : FoodItem
    {

        public override float Calories => 50;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 13,
            Fat = 0,
            Protein = 0,
            Vitamins = 0
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(96);

    }




    //Recipe


    [RequiresSkill(typeof(MillingSkill), 2)]

    public partial class GroundFlaxseedRecipe : RecipeFamily
    {
        public GroundFlaxseedRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "GroundFlaxseed",  //noloc
                displayName: Localizer.DoStr("Grind Flaxseed"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(FlaxSeedItem), 25, typeof(MillingSkill), typeof(MillingLavishResourcesTalent)),
                    
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<GroundFlaxseedItem>(10),   
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(GroundFlaxseedRecipe),
                start: 2f,
                skillType: typeof(MillingSkill), typeof(MillingFocusedSpeedTalent), typeof(MillingParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Grind Flaxseed"), recipeType: typeof(GroundFlaxseedRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(MillObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
