// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.DynamicValues;




    //Item


    [Serialized]
    [LocDisplayName("Heat Lamp Bulb")]
    [Weight(150)]
    [MaxStackSize(420)]
    [LocDescription("A light bulb filled with an inert gas that heats up the directed space. ")]
    public partial class HeatLampBulbItem : PartItem    
    {
        public override IDynamicValue SkilledRepairCost => skilledRepairCost;
        private static IDynamicValue skilledRepairCost = new ConstantValue(1);


        public override LocString DisplayNamePlural { get { return Localizer.DoStr("Heat Lamps"); } }
        public float ReducesMaxDurabilityByPercent => 0.05f;

    }



    //Recipe


    [RequiresSkill(typeof(GlassworkingSkill), 5)]
    public partial class HeatLampBulbRecipe : RecipeFamily
    {
        public HeatLampBulbRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "HeatLampBulb",  //noloc
                displayName: Localizer.DoStr("Heat Lamp Bulb"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(GlassItem), 2, typeof(GlassworkingSkill), typeof(GlassworkingLavishResourcesTalent)),
                    new IngredientElement(typeof(CopperWiringItem), 5, typeof(GlassworkingSkill), typeof(GlassworkingLavishResourcesTalent)),
                    new IngredientElement(typeof(CeramicMoldItem), 1, typeof(GlassworkingSkill), typeof(GlassworkingLavishResourcesTalent)),
                    

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<HeatLampBulbItem>(1)
                });
            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1f;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(HeatLampBulbRecipe), start: 1f, skillType: typeof(GlassworkingSkill), typeof(GlassworkingFocusedSpeedTalent), typeof(GlassworkingParallelSpeedTalent));

            
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Heat Lamp Bulb"), recipeType: typeof(HeatLampBulbRecipe));
            this.ModsPostInitialize();


    CraftingComponent.AddRecipe(tableType: typeof(GlassworksObject), recipe: this);
    }

    partial void ModsPreInitialize();

    partial void ModsPostInitialize();
}
}