// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Iron Spring")]
    [Weight(20)]
    [MaxStackSize(420)]
    [LocDescription("An iron spring used to create bouncing inventions.")]
    public partial class IronSpringItem : Item
    {


    }



    //Recipe


    [RequiresModule(typeof(AnvilObject))]
    [RequiresSkill(typeof(SmeltingSkill), 4)]
    public partial class IronSpringRecipe : RecipeFamily
    {
        public IronSpringRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "IronSpring",  //noloc
                displayName: Localizer.DoStr("Iron Spring"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(IronBarItem), 1, typeof(SmeltingSkill), typeof(SmeltingLavishResourcesTalent)),
                    

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<IronSpringItem>(3)
                });
            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1f;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);


            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(IronSpringRecipe), start: 1f, skillType: typeof(SmeltingSkill), typeof(SmeltingFocusedSpeedTalent), typeof(SmeltingParallelSpeedTalent));


            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Iron Spring"), recipeType: typeof(IronSpringRecipe));
            this.ModsPostInitialize();


            CraftingComponent.AddRecipe(tableType: typeof(BloomeryObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();

    }
}