// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Glass Jar")]
    [Weight(100)]
    [MaxStackSize(420)]
    [LocDescription("An amazing invention to store food, herbs, and just about whatever you can fit into it.")]
    public partial class JarItem : Item
    {


    }



    //Recipe


    [RequiresSkill(typeof(GlassworkingSkill), 3)]
    public partial class JarRecipe : RecipeFamily
    {
        public JarRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Jar",  //noloc
                displayName: Localizer.DoStr("Glass Jar"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(GlassItem), 3, typeof(GlassworkingSkill), typeof(GlassworkingLavishResourcesTalent)),
                    

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<JarItem>(5)
                });
            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1f;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);


            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(JarRecipe), start: 3f, skillType: typeof(GlassworkingSkill), typeof(GlassworkingFocusedSpeedTalent), typeof(GlassworkingParallelSpeedTalent));


            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Glass Jar"), recipeType: typeof(JarRecipe));
            this.ModsPostInitialize();


            CraftingComponent.AddRecipe(tableType: typeof(GlassworksObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();
    }
}