// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Glass Jar Lid")]
    [Weight(20)]
    [MaxStackSize(420)]
    [LocDescription("A lid for those cool glass jars.")]
    public partial class JarLidItem : Item
    {


    }



    //Recipe


    [RequiresModule(typeof(AnvilObject))]
    [RequiresSkill(typeof(SmeltingSkill), 3)]
    public partial class JarLidRecipe : RecipeFamily
    {
        public JarLidRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "JarLid",  //noloc
                displayName: Localizer.DoStr("Glass Jar Lid"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(CopperBarItem), 3, typeof(SmeltingSkill), typeof(SmeltingLavishResourcesTalent)),
                    new IngredientElement(typeof(ClayMoldItem), 5, typeof(SmeltingSkill), typeof(SmeltingLavishResourcesTalent)),
                    new IngredientElement(typeof(WaxItem), 1, true),


                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<JarLidItem>(5),
                    new CraftingElement<JarItem>(1),


                });
            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1f;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);


            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(JarLidRecipe), start: 3f, skillType: typeof(SmeltingSkill), typeof(SmeltingFocusedSpeedTalent), typeof(SmeltingParallelSpeedTalent));


            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Glass Jar Lid"), recipeType: typeof(JarLidRecipe));
            this.ModsPostInitialize();


            CraftingComponent.AddRecipe(tableType: typeof(BloomeryObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();

    }
}