// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Matches")]
    [Weight(60)]
    [MaxStackSize(420)]
    [LocDescription("Matches for lighting things on fire.")]
    public partial class MatchesItem : Item
    {


    }



    //Recipe


    [RequiresModule(typeof(CarpentryTableObject))]
    [RequiresSkill(typeof(LoggingSkill), 5)]
    public partial class MatchesRecipe : RecipeFamily
    {
        public MatchesRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Matches",  //noloc
                displayName: Localizer.DoStr("Matches"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement("WoodBoard", 5, typeof(LoggingSkill), typeof(CarpentryLavishResourcesTalent)),
                    new IngredientElement(typeof(WaxItem), 1, true),
                    new IngredientElement(typeof(CrushedSulfurItem), 3, typeof(LoggingSkill), typeof(CarpentryLavishResourcesTalent)),
                    
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<MatchesItem>(50),
                    new CraftingElement<JarItem>(1),
                });
            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1f;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);


            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(MatchesRecipe), start: 5f, skillType: typeof(LoggingSkill), typeof(CarpentryFocusedSpeedTalent), typeof(CarpentryParallelSpeedTalent));


            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Matches"), recipeType: typeof(MatchesRecipe));
            this.ModsPostInitialize();


            CraftingComponent.AddRecipe(tableType: typeof(SawmillObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();

    }
}