// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;




    //Item


    [Serialized]
    [LocDisplayName("Scissors")]
    [Weight(100)]
    [MaxStackSize(420)]
    [LocDescription("Scissors for cutting things.")]
    public partial class ScissorsItem : Item
    {


    }



    //Recipe


    [RequiresModule(typeof(AnvilObject))]
    [RequiresSkill(typeof(BlacksmithSkill), 1)]
    public partial class ScissorsRecipe : RecipeFamily
    {
        public ScissorsRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Scissors",  //noloc
                displayName: Localizer.DoStr("Scissors"),


                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(IronBarItem), 2, typeof(BlacksmithSkill), typeof(BlacksmithLavishResourcesTalent)),
                    new IngredientElement("WoodBoard", 2, typeof(BlacksmithSkill), typeof(BlacksmithLavishResourcesTalent)),
                    new IngredientElement(typeof(LeatherHideItem), 1, typeof(BlacksmithSkill), typeof(BlacksmithLavishResourcesTalent)),
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<ScissorsItem>(1)
                });
            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1f;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(ScissorsRecipe), start: 2f, skillType: typeof(BlacksmithSkill), typeof(BlacksmithFocusedSpeedTalent), typeof(BlacksmithParallelSpeedTalent));

            
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Scissors"), recipeType: typeof(ScissorsRecipe));
            this.ModsPostInitialize();


            CraftingComponent.AddRecipe(tableType: typeof(GrindstoneObject), recipe: this);
       }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();

   }
}