// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Mods.TechTree;
    using Eco.Shared.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;






    //SelfImprovement Focused Workflow Talent


    [Serialized]
    [LocDisplayName("Focused Workflow: Self Improvement")]
    [LocDescription("Doubles the speed of related tables when alone.")]
    public partial class SelfImprovementFocusedWorkflowTalentGroup : TalentGroup
    {

        public SelfImprovementFocusedWorkflowTalentGroup()
        {
            Talents = new Type[]
            {

            typeof(SelfImprovementFocusedSpeedTalent),


            };
            this.OwningSkill = typeof(SelfImprovementSkill);
            this.Level = 5;
        }
    }


    [Serialized]
    public partial class SelfImprovementFocusedSpeedTalent : FocusedWorkflowTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(SelfImprovementFocusedWorkflowTalentGroup); } }
        public SelfImprovementFocusedSpeedTalent()
        {
            this.Value = 0.5f;
        }
    }




    //SelfImprovement Parallel Processing Talent


    [Serialized]
    [LocDisplayName("Parallel Processing: Self Improvement")]
    [LocDescription("Increases the crafting speed of identical tables when they share a room by 20 percent.")]
    public partial class SelfImprovementParallelProcessingTalentGroup : TalentGroup
    {

        public SelfImprovementParallelProcessingTalentGroup()
        {
            Talents = new Type[]
            {

            typeof(SelfImprovementParallelSpeedTalent),


            };
            this.OwningSkill = typeof(SelfImprovementSkill);
            this.Level = 5;
        }
    }


    [Serialized]
    public partial class SelfImprovementParallelSpeedTalent : ParallelProcessingTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(SelfImprovementParallelProcessingTalentGroup); } }
        public SelfImprovementParallelSpeedTalent()
        {
            this.Value = 0.8f;
        }
    }




    //SelfImprovement Lavish Workspace Talent


    [Serialized]
    [LocDisplayName("Lavish Workspace: Self Improvement")]
    [LocDescription("Increases the tier requirement of tables by 0.2, but reduces the resources needed by 5 percent.")]
    public partial class SelfImprovementLavishWorkspaceTalentGroup : TalentGroup
    {

        public SelfImprovementLavishWorkspaceTalentGroup()
        {
            Talents = new Type[]
            {

            typeof(SelfImprovementLavishResourcesTalent),

            typeof(SelfImprovementLavishReqTalent),

            };
            this.OwningSkill = typeof(SelfImprovementSkill);
            this.Level = 7;
        }
    }


    [Serialized]
    public partial class SelfImprovementLavishResourcesTalent : LavishWorkspaceTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(SelfImprovementLavishWorkspaceTalentGroup); } }
        public SelfImprovementLavishResourcesTalent()
        {
            this.Value = 0.95f;
        }
    }

    [Serialized]
    public partial class SelfImprovementLavishReqTalent : LavishWorkspaceTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(SelfImprovementLavishWorkspaceTalentGroup); } }
        public SelfImprovementLavishReqTalent()
        {
            this.Value = 0.2f;
        }
    }





    //SelfImprovement Frugal Workspace Talent



    [Serialized]
    [LocDisplayName("Frugal Workspace: Self Improvement")]
    [LocDescription("Lowers the tier requirement of related tables by 0.2.(Only applies to claimed workstations)")]
    public class SelfImprovementFrugalWorkspaceTalentGroup : TalentGroup
    {

        public SelfImprovementFrugalWorkspaceTalentGroup()
        {
            this.Talents = new Type[1]
            {
        typeof (SelfImprovementFrugalReqTalent)
            };
            this.OwningSkill = typeof(SelfImprovementSkill);
            this.Level = 7;
        }
    }

    [Serialized]
    public class SelfImprovementFrugalReqTalent : FrugalWorkspaceTalent
    {
        public override bool Base
        {
            get
            {
                return false;
            }
        }

        public override Type TalentGroupType
        {
            get
            {
                return typeof(SelfImprovementFrugalWorkspaceTalentGroup);
            }
        }

        public SelfImprovementFrugalReqTalent()
        {
            this.Value = -0.2f;
        }
    }

}