// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Interactions;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Gameplay.Pipes.LiquidComponents;
    using Eco.Gameplay.Pipes.Gases;
    using Eco.Shared;
    using Eco.Shared.Math;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.Shared.Items;
    using Eco.Shared.Networking;
    using Eco.Gameplay.Pipes;
    using Eco.World.Blocks;
    using Eco.Gameplay.Housing.PropertyValues;
    using Eco.Gameplay.Civics.Objects;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems.NewTooltip;
    using Eco.Core.Controller;
    using Eco.Core.Utils;
	using Eco.Gameplay.Components.Storage;
    using static Eco.Gameplay.Housing.PropertyValues.HomeFurnishingValue;
    using static Eco.Gameplay.Components.PartsComponent;
    using Eco.Gameplay.Items.Recipes;

    [Serialized]
    [RequireComponent(typeof(OnOffComponent))]
    [RequireComponent(typeof(PropertyAuthComponent))]
	[RequireComponent(typeof(PowerGridComponent))]
    [RequireComponent(typeof(PowerConsumptionComponent))]
    [RequireComponent(typeof(LinkComponent))]
	[RequireComponent(typeof(CraftingComponent))]
    [RequireComponent(typeof(HousingComponent))]
	[RequireComponent(typeof(PluginModulesComponent))]
    [RequireComponent(typeof(ForSaleComponent))]
    [RequireComponent(typeof(PartsComponent))]
    [RequireComponent(typeof(RoomRequirementsComponent))]
    [RequireRoomContainment]
    [RequireRoomVolume(5)]
    [RequireRoomMaterialTier(2.8f)]
    [Tag("Usable")]
    [Ecopedia("Housing Objects", "Kitchen", subPageName: "Dehydrator Item")]
    [RepairRequiresSkill(typeof(MechanicsSkill), 1)]
    [RepairRequiresSkill(typeof(SelfImprovementSkill), 4)]
    public partial class DehydratorObject : WorldObject, IRepresentsItem
    {
        public virtual Type RepresentedItemType => typeof(DehydratorItem);
        public override LocString DisplayName => Localizer.DoStr("Dehydrator");

        protected override void Initialize()
        {
            this.ModsPreInitialize();
            this.GetComponent<PowerConsumptionComponent>().Initialize(60);
            this.GetComponent<PowerGridComponent>().Initialize(10, new ElectricPower());
            this.GetComponent<HousingComponent>().HomeValue = DehydratorItem.homeValue;
            this.ModsPostInitialize();

            {
                this.GetComponent<PartsComponent>().Config(() => LocString.Empty, new PartInfo[]
                   {
                                        new() { TypeName = nameof(IronGearItem), Quantity = 1},
                                       });

            }


        }


        partial void ModsPreInitialize();

        partial void ModsPostInitialize();

    }

    [Serialized]
    [LocDisplayName("Dehydrator")]
    [LocDescription("A Dehydrator to blend things in.  Requires electricity.")]
	[IconGroup("World Object Minimap")]
    [Ecopedia("Housing Objects", "Kitchen", createAsSubPage: true)]
    [Tag("Housing")]
    [Weight(500)] // Defines how heavy Dehydrator is.
	[MaxStackSize(200)]
	[AllowPluginModules(Tags = new[] { "AdvancedUpgrade" }, ItemTypes = new[] { typeof(CookingUpgradeItem), typeof(MixologyUpgradeItem), typeof(AdvancedCookingUpgradeItem) })] //noloc
    public partial class DehydratorItem : WorldObjectItem<DehydratorObject>
    {
		[NewTooltip(CacheAs.SubType, 7)] public static LocString PowerConsumptionTooltip() => Localizer.Do($"Consumes: {Text.Info(60)}w of {new ElectricPower().Name} power.");
  
        public override HomeFurnishingValue HomeValue => homeValue;
        public static readonly HomeFurnishingValue homeValue = new HomeFurnishingValue()
		
        {
            ObjectName                              = typeof(DehydratorObject).UILink(),
            Category                                = HousingConfig.GetRoomCategory("Kitchen"),
            BaseValue                               = 2f,
            TypeForRoomLimit                        = Localizer.DoStr("Electric appliances"),
            DiminishingReturnMultiplier                = 0.5f
            
        };
		
    }

    [RequiresSkill(typeof(MechanicsSkill), 2)]
    [Ecopedia("Housing Objects", "Kitchen", subPageName: "Dehydrator Item")]
    public partial class DehydratorRecipe : RecipeFamily
    {
        public DehydratorRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Dehydrator",  //noloc
                displayName: Localizer.DoStr("Dehydrator"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(IronPlateItem), 8, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
					new IngredientElement(typeof(ScrewsItem), 10, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
					new IngredientElement(typeof(IronGearItem), 6, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
					new IngredientElement(typeof(CopperWiringItem), 20, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
					new IngredientElement(typeof(GlassItem), 2, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<DehydratorItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 30f; // Defines how much experience is gained when crafted.
            
            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(50, typeof(MechanicsSkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(DehydratorRecipe), start: 5, skillType: typeof(MechanicsSkill), typeof(MechanicsFocusedSpeedTalent), typeof(MechanicsParallelSpeedTalent));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Dehydrator"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Dehydrator"), recipeType: typeof(DehydratorRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(MachinistTableObject), recipe: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
