// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Cannabis-Infused Cheesy Bread w/ Marinara Dipping Sauce")]
    [Tag("Cannabis")]
    [Weight(100)]
    [MaxStackSize(420)]
    [Tag("Food")]
    [LocDescription("Dough pressed out with a cannabis cooking oil base and cheese rained down on top.  Comes with a side of marinara sauce.")]
    public partial class CannabisInfusedCheesyBreadItem : FoodItem
    {

        public override float Calories => 1200;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 31,
            Fat = 25,
            Protein = 13,
            Vitamins = 15
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);

    }




    //Recipe

    [RequiresModule(typeof(KitchenObject))]
    [RequiresSkill(typeof(AdvancedBakingSkill), 2)]

    public partial class CannabisInfusedCheesyBreadRecipe : RecipeFamily
    {
        public CannabisInfusedCheesyBreadRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CannabisInfusedCheesyBread",  //noloc
                displayName: Localizer.DoStr("Cannabis-Infused Cheesy Bread w/ Marinara Dipping Sauce"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(LeavenedDoughItem), 10, typeof(AdvancedBakingSkill), typeof(AdvancedBakingLavishResourcesTalent)),
                    new IngredientElement(typeof(CannabisCookingOilItem), 1, true),
                    new IngredientElement(typeof(SunCheeseItem), 8, typeof(AdvancedBakingSkill), typeof(AdvancedBakingLavishResourcesTalent)),
                    new IngredientElement(typeof(TomatoItem), 15, typeof(AdvancedBakingSkill), typeof(AdvancedBakingLavishResourcesTalent)),
                    new IngredientElement(typeof(BeetGreensItem), 7, typeof(AdvancedBakingSkill), typeof(AdvancedBakingLavishResourcesTalent)),
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<CannabisInfusedCheesyBreadItem>(5),
                    new CraftingElement<JarItem>(1),
                    new CraftingElement<JarLidItem>(1),

                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(CannabisInfusedCheesyBreadRecipe),
                start: 3f,
                skillType: typeof(AdvancedBakingSkill), typeof(AdvancedBakingFocusedSpeedTalent), typeof(AdvancedBakingParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Cannabis-Infused Cheesy Bread w/ Marinara Dipping Sauce"), recipeType: typeof(CannabisInfusedCheesyBreadRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(BakeryOvenObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
