// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Cannabis-Infused Stir-Fry")]
    [Tag("Cannabis")]
    [Weight(100)]
    [MaxStackSize(420)]
    [Tag("Food")]
    [LocDescription("Cannabis-infused stir fry with vegetables and meat.")]
    public partial class CannabisInfusedStirFryItem : FoodItem
    {

        public override float Calories => 1100;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 23,
            Fat = 23,
            Protein = 25,
            Vitamins = 24,
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);

    }




    //Recipe


    [RequiresSkill(typeof(CookingSkill), 5)]

    public partial class CannabisInfusedStirFryRecipe : RecipeFamily
    {
        public CannabisInfusedStirFryRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CannabisInfusedStirFry",  //noloc
                displayName: Localizer.DoStr("Cannabis-Infused Stir-Fry"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(CannabisCookingOilItem), 1, true),
                    new IngredientElement(typeof(PreparedMeatItem), 10, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),
                    new IngredientElement("Vegetable", 25, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),
                    new IngredientElement("Fungus", 25, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),
                    new IngredientElement(typeof(RiceNoodlesItem), 15, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<CannabisInfusedStirFryItem>(5),
                    new CraftingElement<JarItem>(1),
                    new CraftingElement<JarLidItem>(1),

                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(CannabisInfusedStirFryRecipe),
                start: 3f,
                skillType: typeof(CookingSkill), typeof(CookingFocusedSpeedTalent), typeof(CookingParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Cannabis-Infused Stir-Fry"), recipeType: typeof(CannabisInfusedStirFryRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CastIronStoveObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
