// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Cannabis-Infused Spring Risotto")]
    [Tag("Cannabis")]
    [Weight(100)]
    [MaxStackSize(420)]
    [Tag("Food")]
    [LocDescription("A lovely spring risotto infused with cannabis cooking oil.")]
    public partial class CannabisInfusedSpringRisottoItem : FoodItem
    {

        public override float Calories => 1100;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 30,
            Fat = 20,
            Protein = 21,
            Vitamins = 27
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);

    }




    //Recipe


    [RequiresSkill(typeof(AdvancedCookingSkill), 1)]

    public partial class CannabisInfusedSpringRisottoRecipe : RecipeFamily
    {
        public CannabisInfusedSpringRisottoRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CannabisInfusedSpringRisotto",  //noloc
                displayName: Localizer.DoStr("Cannabis-Infused Spring Risotto"),

                ingredients: new List<IngredientElement>
                {                    
                    new IngredientElement(typeof(CannabisCookingOilItem), 1, true),
                    new IngredientElement(typeof(RiceItem), 25, typeof(AdvancedCookingSkill), typeof(AdvancedCookingLavishResourcesTalent)),
                    new IngredientElement(typeof(VegetableStockItem), 3, typeof(AdvancedCookingSkill), typeof(AdvancedCookingLavishResourcesTalent)),
                    new IngredientElement(typeof(SunCheeseItem), 7, typeof(AdvancedCookingSkill), typeof(AdvancedCookingLavishResourcesTalent)),                    
                    new IngredientElement(typeof(BeetGreensItem), 16, typeof(AdvancedCookingSkill), typeof(AdvancedCookingLavishResourcesTalent)),
                    new IngredientElement(typeof(FireweedShootsItem), 17, typeof(AdvancedCookingSkill), typeof(AdvancedCookingLavishResourcesTalent)),
                    new IngredientElement(typeof(FiddleheadsItem), 18, typeof(AdvancedCookingSkill), typeof(AdvancedCookingLavishResourcesTalent)),
                    new IngredientElement(typeof(BeansItem), 15, typeof(AdvancedCookingSkill), typeof(AdvancedCookingLavishResourcesTalent)),
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<CannabisInfusedSpringRisottoItem>(5),
                    new CraftingElement<JarItem>(1),
                    new CraftingElement<JarLidItem>(1),

                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(CannabisInfusedSpringRisottoRecipe),
                start: 5f,
                skillType: typeof(AdvancedCookingSkill), typeof(AdvancedCookingFocusedSpeedTalent), typeof(AdvancedCookingParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Cannabis-Infused Spring Risotto"), recipeType: typeof(CannabisInfusedSpringRisottoRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(StoveObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
