// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Cannabis Cooking Oil")]
    [Tag("Cannabis")]
    [Weight(120)]
    [MaxStackSize(420)]
    [LocDescription("Cooking oil infused with decarbed cannabis.")]
    public partial class CannabisCookingOilItem : FoodItem
    {

        public override float Calories => 0;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 0,
            Fat = 10,
            Protein = 0,
            Vitamins = 0
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(420);

    }




    //Recipe

  
    [RequiresSkill(typeof(CookingSkill), 4)]

    public partial class CannabisCookingOilRecipe : RecipeFamily
    {
        public CannabisCookingOilRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CannabisCookingOil",  //noloc
                displayName: Localizer.DoStr("Cannabis Cooking Oil"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(OilItem), 4, true),
                    new IngredientElement(typeof(DecarboxylatedCannabisItem), 20, true),
                    new IngredientElement(typeof(HempCheeseclothItem), 1, true),
                    new IngredientElement(typeof(JarItem), 5, true),
                    new IngredientElement(typeof(JarLidItem), 5, true),



                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<CannabisCookingOilItem>(5),
                    new CraftingElement<HempCheeseclothItem>(1),


                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(CannabisCookingOilRecipe),
                start: 4f,
                skillType: typeof(CookingSkill), typeof(CookingFocusedSpeedTalent), typeof(CookingParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Cannabis Cooking Oil"), recipeType: typeof(CannabisCookingOilRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CastIronStoveObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
