// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Cannabis Bud")]
    [Tag("Cannabis")]
    [Weight(100)]
    [MaxStackSize(420)]
    [LocDescription("After cutting away the leaves and main stem, you have the bud core of the Cannabis Plant")]
    public partial class CannabisBudItem : FoodItem
    {

        public override float Calories => 100;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 0,
            Fat = 0,
            Protein = 0,
            Vitamins = 0
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(100);

    }




    //Recipe


    [RequiresSkill(typeof(SelfImprovementSkill), 3)]

    public partial class CannabisBudRecipe : RecipeFamily
    {
        public CannabisBudRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CannabisBud",  //noloc
                displayName: Localizer.DoStr("1st - Process the Cannabis Plant"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(CannabisPlantItem), 1, true),
                    new IngredientElement(typeof(ScissorsItem), 1, true),

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<CannabisBudItem>(1),
                    new CraftingElement<CannabisLeavesItem>(20),
                    new CraftingElement<ScissorsItem>(1),
                    new CraftingElement<PlanterPotRoundItem>(1),
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(CannabisBudRecipe),
                start: 3f,
                skillType: typeof(SelfImprovementSkill), typeof(SelfImprovementFocusedSpeedTalent), typeof(SelfImprovementParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("1st - Process the Cannabis Plant"), recipeType: typeof(CannabisBudRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CannabisWorkbenchObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
