// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Cannabis Leaves")]
    [Tag("Cannabis")]
    [Weight(32)]
    [MaxStackSize(420)]
    [LocDescription("Leaves and stems from a Cannabis Plant.")]
    public partial class CannabisLeavesItem : FoodItem
    {

        public override float Calories => 10;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 4,
            Fat = 2,
            Protein = 0,
            Vitamins = 1
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(120);

    }




   
}
