// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Cannabis Joint")]
    [Tag("Cannabis")]
    [Weight(24)]
    [MaxStackSize(420)]
    [LocDescription("That wonderful cannabis rolled into smokable joints.  Be careful, it will make you very hungry.  :P ")]
    public partial class CannabisJointItem : FoodItem
    {

        public override float Calories => -500;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 0,
            Fat = 0,
            Protein = 0,
            Vitamins = 0
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);

    }




    //Recipe


    [RequiresSkill(typeof(SelfImprovementSkill), 4)]
    
    public partial class CannabisJointRecipe : RecipeFamily
    {
        public CannabisJointRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CannabisJoint",  //noloc
                displayName: Localizer.DoStr("Roll Cannabis Joints"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(GroundCannabisItem), 32, true),
                    new IngredientElement(typeof(RollingPapersItem), 1, true),
                    new IngredientElement(typeof(MatchesItem), 2, typeof(SelfImprovementSkill), typeof(SelfImprovementLavishResourcesTalent)),


                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<CannabisJointItem>(32),
                    
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(CannabisJointRecipe),
                start: 3f,
                skillType: typeof(SelfImprovementSkill), typeof(SelfImprovementFocusedSpeedTalent), typeof(SelfImprovementParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Roll Joints"), recipeType: typeof(CannabisJointRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CannabisWorkbenchObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
