// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Dried Cannabis Bud")]
    [Tag("Cannabis")]
    [Weight(120)]
    [MaxStackSize(420)]
    [LocDescription("A bud of the cannabis plant that has been cut and dried.")]
    public partial class DriedCannabisBudItem : FoodItem
    {

        public override float Calories => 70;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 6,
            Fat = 3,
            Protein = 0,
            Vitamins = 2
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(120);

    }




    //Recipe


    [RequiresSkill(typeof(SelfImprovementSkill), 3)]
    
    public partial class DriedCannabisBudRecipe : RecipeFamily
    {
        public DriedCannabisBudRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "DriedCannabisBud",  //noloc
                displayName: Localizer.DoStr("2nd - Dry the Cannabis Bud"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(CannabisBudItem), 5, true),
                    new IngredientElement(typeof(HempYarnItem), 1, typeof(SelfImprovementSkill), typeof(SelfImprovementLavishResourcesTalent)),                    
                    new IngredientElement(typeof(ScissorsItem), 1, true),

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<DriedCannabisBudItem>(5),
                    new CraftingElement<ScissorsItem>(1),
                    
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(DriedCannabisBudRecipe),
                start: 20f,
                skillType: typeof(SelfImprovementSkill), typeof(SelfImprovementFocusedSpeedTalent), typeof(SelfImprovementParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("2nd - Dry the Cannabis Bud"), recipeType: typeof(DriedCannabisBudRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CannabisWorkbenchObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
