// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Ground Cannabis")]
    [Tag("Cannabis")]
    [Weight(72)]
    [MaxStackSize(420)]
    [LocDescription("Cannabis buds that have been grinded down. ")]
    public partial class GroundCannabisItem : FoodItem
    {

        public override float Calories => 20;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 2,
            Fat = 2,
            Protein = 0,
            Vitamins = 2
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);

    }




    //Recipe


    [RequiresSkill(typeof(SelfImprovementSkill), 4)]

    public partial class GroundCannabisRecipe : RecipeFamily
    {
        public GroundCannabisRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "GroundCannabis",  //noloc
                displayName: Localizer.DoStr("Grind the Cannabis Buds"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(JarOfCuredCannabisBudsItem), 1, true),
                    new IngredientElement(typeof(GrinderItem), 1, true),



                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<GroundCannabisItem>(105),
                    new CraftingElement<GrinderItem>(1),
                    new CraftingElement<JarItem>(1),
                    new CraftingElement<JarLidItem>(1),

                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(GroundCannabisRecipe),
                start: 2,
                skillType: typeof(SelfImprovementSkill), typeof(SelfImprovementFocusedSpeedTalent), typeof(SelfImprovementParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Grind the Cannabis Buds"), recipeType: typeof(GroundCannabisRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CannabisWorkbenchObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
