// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Jar Of Cured Cannabis Buds")]
    [Tag("Cannabis")]
    [Weight(420)]
    [MaxStackSize(420)]
    [LocDescription("Cannabis buds that have been cured with time in a jar.")]
    public partial class JarOfCuredCannabisBudsItem : FoodItem
    {

        public override float Calories => 100;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 10,
            Fat = 8,
            Protein = 0,
            Vitamins = 5
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(420);

    }




    //Recipe


    [RequiresSkill(typeof(SelfImprovementSkill), 4)]
    
    public partial class JarOfCuredCannabisBudsRecipe : RecipeFamily
    {
        public JarOfCuredCannabisBudsRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "JarOfCuredCannabisBuds",  //noloc
                displayName: Localizer.DoStr("4th - Cure the Cannabis Buds"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(TrimmedCannabisBudItem), 420, true),
                    new IngredientElement(typeof(JarItem), 4, true),
                    new IngredientElement(typeof(JarLidItem), 4, true),

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<JarOfCuredCannabisBudsItem>(4),                    
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 2;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(JarOfCuredCannabisBudsRecipe),
                start: 45f,
                skillType: typeof(SelfImprovementSkill), typeof(SelfImprovementFocusedSpeedTalent), typeof(SelfImprovementParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("4th - Cure the Cannabis Buds"), recipeType: typeof(JarOfCuredCannabisBudsRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CannabisWorkbenchObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
