// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;




    //FoodItem


    [Serialized]
    [LocDisplayName("Trimmed Cannabis Bud")]
    [Tag("Cannabis")]
    [Weight(72)]
    [MaxStackSize(420)]
    [LocDescription("Cannabis plant that has had its leaves and stems trimmed away to the buds.")]
    public partial class TrimmedCannabisBudItem : FoodItem
    {

        public override float Calories => 20;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 5,
            Fat = 3,
            Protein = 0,
            Vitamins = 2
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(90);

    }




    //Recipe


    [RequiresSkill(typeof(SelfImprovementSkill), 3)]
    
    public partial class TrimmedCannabisBudRecipe : RecipeFamily
    {
        public TrimmedCannabisBudRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "TrimmedCannabisBud",  //noloc
                displayName: Localizer.DoStr("3rd - Trim the Cannabis Bud into Smaller Buds."),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(DriedCannabisBudItem), 1, typeof(SelfImprovementSkill), typeof(SelfImprovementLavishResourcesTalent)),
                    new IngredientElement(typeof(ScissorsItem), 1, true),

                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<TrimmedCannabisBudItem>(42),
                    new CraftingElement<CannabisLeavesItem>(7),
                    new CraftingElement<ScissorsItem>(1),
                    
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(420);

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(TrimmedCannabisBudRecipe),
                start: 4f,
                skillType: typeof(SelfImprovementSkill), typeof(SelfImprovementFocusedSpeedTalent), typeof(SelfImprovementParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("3rd - Trim the Cannabis Bud into Smaller Buds."), recipeType: typeof(TrimmedCannabisBudRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(CannabisWorkbenchObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
